# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobackup < Formula
  desc "GoBackup"
  homepage ""
  version "2.15.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/itgcloud/gobackup/releases/download/v2.15.2/gobackup-darwin-amd64.tar.gz"
      sha256 "7d32cf450b154e3765457dc8ddd32433cf8c4e0e6f6fc7696d491968e6fd2f6c"

      def install
        bin.install "gobackup"
      end
    end
    on_arm do
      url "https://github.com/itgcloud/gobackup/releases/download/v2.15.2/gobackup-darwin-arm64.tar.gz"
      sha256 "d851d57a274d5082deacf31b06cff156ff4e9c75a03eb3247750c61273bee32d"

      def install
        bin.install "gobackup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itgcloud/gobackup/releases/download/v2.15.2/gobackup-linux-amd64.tar.gz"
        sha256 "8d205f5b036c7a3e2bf5574f494011351c4c105c8c51624230af71cc258e8805"

        def install
          bin.install "gobackup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itgcloud/gobackup/releases/download/v2.15.2/gobackup-linux-arm64.tar.gz"
        sha256 "bf7b70279afecc95d843cf621dba6ef70ee68d2247bd893c2e30ce4b7201d5aa"

        def install
          bin.install "gobackup"
        end
      end
    end
  end
end
