# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobackup < Formula
  desc "GoBackup"
  homepage ""
  version "2.16.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.16.0/gobackup-darwin-amd64.tar.gz"
      sha256 "167e389c7c69c63d5b1d583d491fa1c1429033d477415f4a5aa4be49672a554f"

      def install
        bin.install "gobackup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.16.0/gobackup-darwin-arm64.tar.gz"
      sha256 "7bda1586cadc164d1c8dfa6a016779ffeeaff16c38adbce050f2943dffa1da2e"

      def install
        bin.install "gobackup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itgcloud/gobackup/releases/download/v2.16.0/gobackup-linux-amd64.tar.gz"
        sha256 "35989949f2f21be34ec8e2ee94a685ba0de9935e1ef60a5f4d9e55080cc6c395"

        def install
          bin.install "gobackup"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/itgcloud/gobackup/releases/download/v2.16.0/gobackup-linux-arm64.tar.gz"
        sha256 "a3403bc74b17398bc2a7c09c051816c29d6086848517e53f83189ce5024f4a7f"

        def install
          bin.install "gobackup"
        end
      end
    end
  end
end
