# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobackup < Formula
  desc "GoBackup"
  homepage ""
  version "2.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.12.0/gobackup-darwin-amd64.tar.gz"
      sha256 "631123d06cdd9ef591350b93c2e4b9d796989fba70c7e5a8ac529dd5b2bb1d4c"

      def install
        bin.install "gobackup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.12.0/gobackup-darwin-arm64.tar.gz"
      sha256 "3c06f03c6402a6653f2aa538a70212bcfbcbae44447d01ad50d0247610589bdb"

      def install
        bin.install "gobackup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.12.0/gobackup-linux-amd64.tar.gz"
      sha256 "f320e6af3120f5c069a8f2fa26e89954be45ee713562941cfde69ae48754cb6b"

      def install
        bin.install "gobackup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.12.0/gobackup-linux-arm64.tar.gz"
      sha256 "85feecca8b0a32b1531ad7521f2df3a4693a9a057b2fbaea1b8c3ca8e6b7947c"

      def install
        bin.install "gobackup"
      end
    end
  end
end
