# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobackup < Formula
  desc "GoBackup"
  homepage ""
  version "2.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.15.1/gobackup-darwin-amd64.tar.gz"
      sha256 "814aed37a3f7a69163a2c567118ee51bff13057d34ffe265ac974c71ff959997"

      def install
        bin.install "gobackup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.15.1/gobackup-darwin-arm64.tar.gz"
      sha256 "1727ead6615970b1e4d0fad736999a6e20a00b69ee423f07029ce3542083188e"

      def install
        bin.install "gobackup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.15.1/gobackup-linux-amd64.tar.gz"
      sha256 "80aa7a86a12d9ae90d6b873a33a02040c231e40330b8aeac4621d49619194d7a"

      def install
        bin.install "gobackup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itgcloud/gobackup/releases/download/v2.15.1/gobackup-linux-arm64.tar.gz"
      sha256 "203a10bb2e369e2b5b676b8c37911e4f91b8eccc5d1526968246a1552d006a1a"

      def install
        bin.install "gobackup"
      end
    end
  end
end
